---
version: '3.7'

services:
  app:
    container_name: graphql-app-backend
    build:
      context: ./app
      target: build
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: graphql-app-development
      CORS_ALLOW_ORIGIN: http://localhost:8081
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    tty: true

  db:
    platform: linux/x86_64 #for m1Tip
    container_name: graphql-app-db
    image: mysql:8.0.25
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      # MYSQL_USER: testuser
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql-app-development
    ports:
      - 3306:3306
    tty: true
