import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const useCount = () => {
  const [count, setCount] = useState(0)
  const countUp = () => setCount((c) => c + 1)
  return [count, countUp] as const
}

const useCurrentDate = (interval: any) => {
  const [date, setDate] = useState(new Date())

  useEffect(()=>{
    const timer = setInterval(()=>{
      setDate(new Date());
    }, interval)

    return () => clearInterval(timer)
  }, [setDate])

  return date
}

export default function Home() {
  const [count, setCount] = useState(0)
  // console.log(count)
  const [customCount, customCountUp] = useCount()
  // const [date, setDate] = useState(new Date())

  // useEffect(()=>{
  //   const timer = setInterval(()=>{
  //     setDate(new Date())
  //   }, 1000);

  //   return () => clearInterval(timer)
  // }, [setDate])

  const date = useCurrentDate(1000)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={()=>setCount(count+1)}>
        {count}
      </button>
      <button onClick={customCountUp}>
        custom{customCount}
      </button>
      <div>{date.toLocaleTimeString()}</div>
      <main className={styles.main}>
        <div>
          <Link href={`/tasks`}>
            Tasks
          </Link>
        </div>
      </main>
    </div>
  )
}
